// <auto-generated />
using GeekShopping.ProductAPI.Model.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GeekShopping.ProductAPI.Migrations
{
    [DbContext(typeof(PostgreSQLContext))]
    partial class PostgreSQLContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GeekShopping.ProductAPI.Model.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("category_name");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("image_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.HasKey("Id");

                    b.ToTable("product");

                    b.HasData(
                        new
                        {
                            Id = 2L,
                            CategoryName = "Boné",
                            Description = "O Boné Americano Black da Diivoo é a escolha perfeita para quem busca atitude e versatilidade no streetwear.",
                            ImageURL = "https://images.tcdn.com.br/img/img_prod/1377455/bone_americano_red_9_1_0e4486f66b5f79247faa89a78bdc7067.jpg",
                            Name = "Boné Americano Red",
                            Price = 89.9m
                        },
                        new
                        {
                            Id = 3L,
                            CategoryName = "Boné",
                            Description = "O Boné Americano Black da Diivoo é a escolha perfeita para quem busca atitude e versatilidade no streetwear.",
                            ImageURL = "https://images.tcdn.com.br/img/img_prod/1377455/bone_americano_red_9_1_0e4486f66b5f79247faa89a78bdc7067.jpg",
                            Name = "Boné Americano Black Light",
                            Price = 89.9m
                        },
                        new
                        {
                            Id = 4L,
                            CategoryName = "Boné",
                            Description = "O Boné Americano Black da Diivoo é a escolha perfeita para quem busca atitude e versatilidade no streetwear.",
                            ImageURL = "https://images.tcdn.com.br/img/img_prod/1377455/bone_americano_red_9_1_0e4486f66b5f79247faa89a78bdc7067.jpg",
                            Name = "Boné Americano Cinza",
                            Price = 89.9m
                        },
                        new
                        {
                            Id = 5L,
                            CategoryName = "Boné",
                            Description = "O Boné Americano Black da Diivoo é a escolha perfeita para quem busca atitude e versatilidade no streetwear.",
                            ImageURL = "https://images.tcdn.com.br/img/img_prod/1377455/bone_americano_red_9_1_0e4486f66b5f79247faa89a78bdc7067.jpg",
                            Name = "Boné Americano Bege",
                            Price = 89.9m
                        },
                        new
                        {
                            Id = 6L,
                            CategoryName = "Boné",
                            Description = "O Boné Americano Black da Diivoo é a escolha perfeita para quem busca atitude e versatilidade no streetwear.",
                            ImageURL = "https://images.tcdn.com.br/img/img_prod/1377455/bone_americano_red_9_1_0e4486f66b5f79247faa89a78bdc7067.jpg",
                            Name = "Boné Americano Laranja",
                            Price = 89.9m
                        },
                        new
                        {
                            Id = 7L,
                            CategoryName = "Boné",
                            Description = "O Boné Americano Black da Diivoo é a escolha perfeita para quem busca atitude e versatilidade no streetwear.",
                            ImageURL = "https://images.tcdn.com.br/img/img_prod/1377455/bone_americano_red_9_1_0e4486f66b5f79247faa89a78bdc7067.jpg",
                            Name = "Boné Americano Rosa",
                            Price = 89.9m
                        },
                        new
                        {
                            Id = 8L,
                            CategoryName = "Boné",
                            Description = "O Boné Americano Black da Diivoo é a escolha perfeita para quem busca atitude e versatilidade no streetwear.",
                            ImageURL = "https://images.tcdn.com.br/img/img_prod/1377455/bone_americano_red_9_1_0e4486f66b5f79247faa89a78bdc7067.jpg",
                            Name = "Boné Americano Branco",
                            Price = 89.9m
                        },
                        new
                        {
                            Id = 9L,
                            CategoryName = "Boné",
                            Description = "O Boné Americano Black da Diivoo é a escolha perfeita para quem busca atitude e versatilidade no streetwear.",
                            ImageURL = "https://images.tcdn.com.br/img/img_prod/1377455/bone_americano_red_9_1_0e4486f66b5f79247faa89a78bdc7067.jpg",
                            Name = "Boné Americano Azul",
                            Price = 89.9m
                        },
                        new
                        {
                            Id = 10L,
                            CategoryName = "Boné",
                            Description = "O Boné Americano Black da Diivoo é a escolha perfeita para quem busca atitude e versatilidade no streetwear.",
                            ImageURL = "https://images.tcdn.com.br/img/img_prod/1377455/bone_americano_red_9_1_0e4486f66b5f79247faa89a78bdc7067.jpg",
                            Name = "Boné Americano Amarelo",
                            Price = 89.9m
                        },
                        new
                        {
                            Id = 11L,
                            CategoryName = "Boné",
                            Description = "O Boné Americano Black da Diivoo é a escolha perfeita para quem busca atitude e versatilidade no streetwear.",
                            ImageURL = "https://images.tcdn.com.br/img/img_prod/1377455/bone_americano_red_9_1_0e4486f66b5f79247faa89a78bdc7067.jpg",
                            Name = "Boné Americano Roxo",
                            Price = 89.9m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
